### ISSUE TITLE
Bootstrapping event listeners could be optional

### ISSUE THREAD

**Issue by MikeVaz** [WebReflection/wicked-elements#12]
I explored the source code and found that every time we register an element with `wickedElements.define`  we call [bootstrap](https://github.com/WebReflection/wicked-elements/blob/master/index.js#L450) function to add event listeners.

I understand that it is handy this way but it impacts performance. Can we make it optional?

E.g. we can introduce an extra parameter to provide a list of events we care about.

```javascript
wickedElements.define('selector', obj, ['click', 'touchstart']) 
```

This is one of the blockers for us to use it in production.

**Comment by WebReflection** [comment]
> I explored the source code and found that every time we register an element with wickedElements.define we call bootstrap function to add event listeners.

Nope, bootstrap is called only on unknown elements.
https://github.com/WebReflection/wicked-elements/blob/master/esm/index.js#L64-L66

> I understand that it is handy this way but it impacts performance.

I'd like to see evidence on this claim. Do you have any real-world case to demonstrate performance issue?

Regardless, how is an element supposed to be setup if not through a bootstrap?

> E.g. we can introduce an extra parameter to provide a list of events we care about.

Listeners are defined via objects and their inheritance. If you want just set `click` and `touchstart` you should register the element with an object that has only `onclick` and `ontouchstart` methods.

Everything else is redundant.

**Comment by MikeVaz** [comment]
What if your delegate object is a Web component descendant from `HTMLElement` which already has `onclick` https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onclick

**Comment by WebReflection** [comment]
> What if your delegate object is a Web component ...

I stop you there. That's not how you use this library. You pass an object, not a DOM element.

Can you tell me a single use case for passing a DOM element you don't own as configuration object? 'cause I don't think that's what this library is about, it looks like you rather want to use Custom Elements builtins in that case, so you can use [this polyfill](https://github.com/ungap/custom-elements-builtin) instead of this library.

This library is about **avoiding Custom Elements** because it's an alternative to these, not an enricher of those. There are many other alternatives to this library born, or meant, to enrich Custom Elements, I suggest you look elsewhere, if Custom Elements is your thing.

Or you could start migrating to wicked Elements and never ever pass exotic objects you don't own to as configurator of the registered selector.

**Comment by MikeVaz** [comment]
If you'd slightly tweak and expose bootstrap method as an API it can be used in custom elements too making your library and ideas applicable for a wider variety of cases.

**Comment by WebReflection** [comment]
The `bootstrap` is stringily coupled with wicked elements registry and by contract:

  * it works with [handleEvent pattern](https://github.com/WebReflection/wicked-elements/blob/master/esm/index.js#L100-L102)
  * it uses an [init handler](https://github.com/WebReflection/wicked-elements/blob/master/esm/index.js#L99)
  * it uses the [handleEvent pattern](https://github.com/WebReflection/wicked-elements/blob/master/esm/index.js#L91)
