### ISSUE TITLE
customElements enhancement

### ISSUE THREAD

**Issue by anywhichway** [WebReflection/wicked-elements#15]
@WebReflection Nice work! In the case where I already have customElements or want tags that look like customElements (i.e. don't use is=), a small enhancement would be nice.

If wickedElements is called with a hyphenated name (i.e. a selector that looks like a custom tag name) and a constructor or object, then if it is a function and customElements is available enhance the connectedCallback on the constructor to add any "on" handlers and dispatch to customElements.define. Or, if customElements is not available or the second argument is an object, do a query for all the nodes with the hyphenated name and patch then to be divs with as=<hyphenated name> attribute, then recursively call wickedElements.define with '[as="<hyphenated name>"]` and the function or object. This effectively becomes a partial functional polyfill for customElements.

I have written the wrapper and am loathe to add a package to the ecosystem for such a small enhancement, 25 lines of code. Interested in a pull if I do the work?

**Comment by WebReflection** [comment]
This project has nothing to do with `is-`, that's just an example, any CSS selector would work the same.

**Comment by anywhichway** [comment]
So you are saying that the below is possible and will work automatically even when customElements are not available?

`wickedElements.define("wicked-wicked-element",
      someExistingCustomComponentConstructorOrAnInstanceWithEventHandlers,
     {extends: "button"})`

`<wicked-wicked-element>Even more powerful with less cruft</wicked-wicked-element>`

rather than

`<button is="wicked-wicked-element">Event more powerful with some cruft</wicked-wicked-element>`

**Comment by WebReflection** [comment]
I am saying this project enhance any sort of element, so that you don't need to extend anything, 'cause if a button is part of the selector you define, that's it, it'll be defined as wicked element.

Every node can have 0, 1, or many wicked elements definitions, you never have been able to compose so well with anything else out there, and you can use `onconnected` and `ondisconnected` callback to do anything you want.

This works already with custom elements, and there are no limits in what you can define, so any wrapper would become a limitation instead of an enhancement.

`wickedElements.define("button.wicked", someDefinition);` works already, no need to `extend: "button"`, wicked elements works with absolutely any DOM node.

**Comment by anywhichway** [comment]
@WebReflection OK. Thanks for your attention to this issue. Once again. Great work! I think this provides a really good way to keep visual designers and devs in sync plus awesome encapsulation.

**Comment by WebReflection** [comment]
@anywhichway it's a different approach that has never been seen and somehow superior to any class extends with Custom Elements, and it takes a little while to everyone to wraps their head and thoughts around this, 'cause it has no precedents or alternatives.

If only some big co would take this for a spin, you'd see why the name contains the word _wicked_ 😉
